server:
  port: 8080

spring:
  file:
    upload-dir: C:\졸업전시\GetJobV1.0.1\uploads
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    check-template-location: true

  datasource:
    url: jdbc:mysql://localhost:3306/GetJob?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: honesty1234!


  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  resources:
    static-locations: file:C:/Spring/GetJobV1.0.1/uploads/, classpath:/static/, file:./src/main/resources/static/

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  packages-to-scan: com.example.GetJobV101.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api-docs/
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
